exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "docs",
    "node_modules",
    "site-packages",
    # "tests",
    "venv",
    "*egg-info",
]

line-length = 88
indent-width = 4
# target-version = "py312"  # Uncomment and set the target Python version if needed

[lint]
select = [  # https://docs.astral.sh/ruff/rules/
    "C",  # Complexity
    "D",  # PyDocStyle
    "E",  # PyCodeStyle Errors
    "F",  # PyFlakes
    "W",  # PyCodeStyle Warnings
    "ANN",  # flake8-annotations
    "B",  # flake8-bugbear
    "TC",  # flake8-type-checking
    "PTH",  # flake8-use-pathlib
    "NPY",  # NumPy specific rules
    "TID",  # flake8-tidy-imports
    "SIM",  # flake8-simplify
    "I",  # isort
    "PL",  # PyLint
    "ERA",  # eradicate
]
ignore = ["D105"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
preview = true

[lint.pylint]
max-args = 10

[lint.per-file-ignores]
"tests/*" = ["D100", "D103", "ANN001"]
"*.ipynb" = ["D101", "D102", "D103", "D107", "E402", "I001"]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
