EXCLUDED_CLASSES = [
    "ALGAE",
    "BRIDGE",
    "HARBOUR",
    "WATERTRACK",
    "SHORELINE",
    "SUN_REFLECTION",
    "UNSUPERVISED",
    "WATER",
    "TRASH",
    "OBJECT_REFLECTION",
    "HORIZON",
]